spring:
  application:
    name: learn-spring

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  #== Database settings ==#
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/chat_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  #== Flyway settings ==#
  flyway:
    enabled: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    ms: 18000000

#logging:
#  level:
#    org.springframework.security: TRACE

logging:
  level:
    root: DEBUG



